name: dev_new_my_npm_test

on: 
#     push:
    workflow_dispatch:

env:
     SCRIBE_URL: "https://airflow.dev.scribesecurity.com/scribe-proxy"
     SCRIBE_LOGIN_URL: "https://scribe-hub-dev.us.auth0.com
     SCRIBE_AUDIENCE: "api.dev.scribesecurity.com"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
     id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
         
      - name: Scm generate bom, upload to scribe
        id: valint_bom_scm
#         uses: scribe-security/action-bom@master
        uses: scribe-security/action-bom@dev
        with:
          type: dir
          target: ./
          verbose: 2
          scribe-enable: true
#           scribe-client-id: ${{ secrets.SCRIBE_DEV_CLIENT_ID }}
#           scribe-client-secret: ${{ secrets.SCRIBE_DEV_CLIENT_SECRET }}
          scribe-client-id: 5xIbFlIdJm8FTKa05pSZJpb2yo1FYoPP
          scribe-client-secret: 0HP_B-3SuTk46CZnpXXU5CApN0JPX1UZe3ielnP3utyd-18ZH6y8tqrUtMiXp-7E
          product-key: "000_dev_my_npm"
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}

      - name: build image
        run: |
          docker build -t my-image:latest .
          
      - name: Image generate bom, upload to scribe
        id: valint_bom_image
#         uses: scribe-security/action-bom@master
        uses: scribe-security/action-bom@dev
        with:
          type: docker
          target: my-image:latest
          verbose: 2
          format: attest
          scribe-enable: true
#           scribe-client-id: ${{ secrets.SCRIBE_DEV_CLIENT_ID }}
#           scribe-client-secret: ${{ secrets.SCRIBE_DEV_CLIENT_SECRET }}
          scribe-client-id: 5xIbFlIdJm8FTKa05pSZJpb2yo1FYoPP
          scribe-client-secret: 0HP_B-3SuTk46CZnpXXU5CApN0JPX1UZe3ielnP3utyd-18ZH6y8tqrUtMiXp-7E
          product-key: "000_dev_my_npm"
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}

      - uses: actions/upload-artifact@v2
        with:
          name: scribe-reports
          path: |
            ${{ steps.valint_bom_scm.outputs.OUTPUT_PATH }}
            ${{ steps.valint_bom_image.outputs.OUTPUT_PATH }}
            
      - name: Generate SLSA provenance statement
        id: valint_slsa_statement
#         uses: scribe-security/action-bom@master
        uses: scribe-security/action-bom@dev
        with:
          target: mongo-express:1.0.0-alpha.4
#           format: statement-slsa
          format: attest-slsa
          product-key: "000_dev_my_npm"

      - uses: actions/upload-artifact@v2
        with:
          name: provenance
          path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
