name: Docker Image CI

on: 
    push:
    workflow_dispatch:

# env:
#      SCRIBE_URL: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
#      SCRIBE_LOGIN_URL: "https://scribesec-dev.us.auth0.com"
#      SCRIBE_AUDIENCE: "api.dev.scribesecurity.com"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
         
      - name: Scm generate bom, upload to scribe
        id: valint_bom_scm
        uses: scribe-security/action-bom@master
        with:
          type: dir
          target: ./
          verbose: 2
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_PROD_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_PROD_CLIENT_SECRET }}
          product-key: "0_npm_project"
#           scribe-url: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
#           scribe-login-url: "https://scribesec-dev.us.auth0.com"
#           scribe-audience: "api.dev.scribesecurity.com"

      - name: build image
        run: |
          docker build -t my-image:latest .
          
      - name: Image generate bom, upload to scribe
        id: valint_bom_image
        uses: scribe-security/action-bom@master
        with:
          type: docker
          target: my-image:latest
          verbose: 2
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_PROD_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_PROD_CLIENT_SECRET }}
          product-key: "0_npm_project"
#           scribe-url: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
#           scribe-login-url: "https://scribesec-dev.us.auth0.com"
#           scribe-audience: "api.dev.scribesecurity.com"
