name: prod_my_npm_test

on: 
#     push:
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
     id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
         
      - name: Scm generate bom, upload to scribe
        id: valint_bom_scm
        uses: scribe-security/action-bom@master
        with:
          type: dir
          target: ./
          verbose: 2
          format: statement-cyclonedx-json
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_PROD_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_PROD_CLIENT_SECRET }}
          product-key: "000_prod_my_npm"

      - name: build image
        run: |
          docker build -t my-image:latest .
          
      - name: Image generate bom, upload to scribe
        id: valint_bom_image
        uses: scribe-security/action-bom@master
        with:
          type: docker
          target: my-image:latest
          format: statement-cyclonedx-json
          verbose: 2
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_PROD_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_PROD_CLIENT_SECRET }}
          product-key: "000_prod_my_npm"

      - uses: actions/upload-artifact@v2
        with:
          name: scribe-reports
          path: |
            ${{ steps.valint_bom_scm.outputs.OUTPUT_PATH }}
            ${{ steps.valint_bom_image.outputs.OUTPUT_PATH }}
            
      - name: Generate SLSA provenance statement
        id: valint_slsa_statement
        uses: scribe-security/action-bom@master
        with:
          target: mongo-express:1.0.0-alpha.4
          format: statement-slsa
          product-key: "000_prod_my_npm"

      - uses: actions/upload-artifact@v2
        with:
          name: provenance
          path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
